#!/usr/bin/env bash
# Write config/deploy/aws.env from live Kubernetes ingress/service endpoints.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ROOT}/config/deploy/aws.env"
NAMESPACE="${K8S_NAMESPACE:-routing}"
RELEASE="${HELM_RELEASE:-routing-tier}"
INGRESS_NAME="${INGRESS_NAME:-envoy-router}"

ALB_HOST="$(kubectl get ingress "${INGRESS_NAME}" -n "$NAMESPACE" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
GRPC_SVC="${GRPC_SERVICE:-envoy-router-grpc}"

ALB_HOST="$(kubectl get ingress "${INGRESS_NAME}" -n "$NAMESPACE" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
GRPC_HOST="$(kubectl get svc "${GRPC_SVC}" -n "$NAMESPACE" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"

if [[ -z "$ALB_HOST" ]]; then
  echo "ALB hostname not ready — wait for ingress ${RELEASE} in ${NAMESPACE}" >&2
  exit 1
fi

if [[ -z "$GRPC_HOST" ]]; then
  GRPC_HOST="$ALB_HOST"
fi

cat >"$OUT" <<EOF
# Generated by infra/scripts/write-aws-profile.sh — do not edit by hand.
POD_MANAGER_DEPLOY_TARGET=aws
ENVOY_URL=http://${ALB_HOST}
NEXT_PUBLIC_ENVOY_URL=http://${ALB_HOST}
POD_MANAGER_HOST=${GRPC_HOST}
POD_MANAGER_PORT=8804
POD_MANAGER_GRPC_HOST=${GRPC_HOST}
POD_MANAGER_GRPC_PORT=8804
EOF

echo "Wrote ${OUT}"
cat "$OUT"
