# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pod_manager.v1 import pool_pb2 as pod__manager_dot_v1_dot_pool__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pod_manager/v1/pool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PodManagerServiceStub(object):
    """Control-plane RPCs for pod pool, assignments, and operator config (PM-2).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLease = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/AcquireLease',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/ReleaseLease',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)
        self.GetLease = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/GetLease',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.GetLeaseRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetLeaseResponse.FromString,
                _registered_method=True)
        self.GetBackendPoolAvailability = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/GetBackendPoolAvailability',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityResponse.FromString,
                _registered_method=True)
        self.GetPoolStatus = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/GetPoolStatus',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/Heartbeat',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetRuntimeEnvironment = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/GetRuntimeEnvironment',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentResponse.FromString,
                _registered_method=True)
        self.ListServiceConfig = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/ListServiceConfig',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigResponse.FromString,
                _registered_method=True)
        self.GetServiceConfig = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/GetServiceConfig',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.GetServiceConfigRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.FromString,
                _registered_method=True)
        self.PutServiceConfig = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/PutServiceConfig',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.PutServiceConfigRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.FromString,
                _registered_method=True)
        self.DeleteServiceConfig = channel.unary_unary(
                '/pod_manager.v1.PodManagerService/DeleteServiceConfig',
                request_serializer=pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigRequest.SerializeToString,
                response_deserializer=pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigResponse.FromString,
                _registered_method=True)


class PodManagerServiceServicer(object):
    """Control-plane RPCs for pod pool, assignments, and operator config (PM-2).
    """

    def AcquireLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackendPoolAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutServiceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteServiceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PodManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLease,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
            'GetLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLease,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetLeaseRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.GetLeaseResponse.SerializeToString,
            ),
            'GetBackendPoolAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackendPoolAvailability,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityResponse.SerializeToString,
            ),
            'GetPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolStatus,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.HeartbeatRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetRuntimeEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeEnvironment,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentResponse.SerializeToString,
            ),
            'ListServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceConfig,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigResponse.SerializeToString,
            ),
            'GetServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceConfig,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.GetServiceConfigRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.SerializeToString,
            ),
            'PutServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PutServiceConfig,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.PutServiceConfigRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.SerializeToString,
            ),
            'DeleteServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteServiceConfig,
                    request_deserializer=pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigRequest.FromString,
                    response_serializer=pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pod_manager.v1.PodManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pod_manager.v1.PodManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PodManagerService(object):
    """Control-plane RPCs for pod pool, assignments, and operator config (PM-2).
    """

    @staticmethod
    def AcquireLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/AcquireLease',
            pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.AcquireLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/ReleaseLease',
            pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/GetLease',
            pod__manager_dot_v1_dot_pool__pb2.GetLeaseRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.GetLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackendPoolAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/GetBackendPoolAvailability',
            pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.GetBackendPoolAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/GetPoolStatus',
            pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.GetPoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/Heartbeat',
            pod__manager_dot_v1_dot_pool__pb2.HeartbeatRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/GetRuntimeEnvironment',
            pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.GetRuntimeEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/ListServiceConfig',
            pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.ListServiceConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/GetServiceConfig',
            pod__manager_dot_v1_dot_pool__pb2.GetServiceConfigRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/PutServiceConfig',
            pod__manager_dot_v1_dot_pool__pb2.PutServiceConfigRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.ServiceConfigEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pod_manager.v1.PodManagerService/DeleteServiceConfig',
            pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigRequest.SerializeToString,
            pod__manager_dot_v1_dot_pool__pb2.DeleteServiceConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
