# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from udpa.data.orca.v1 import orca_load_report_pb2 as udpa_dot_data_dot_orca_dot_v1_dot_orca__load__report__pb2
from udpa.service.orca.v1 import orca_pb2 as udpa_dot_service_dot_orca_dot_v1_dot_orca__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in udpa/service/orca/v1/orca_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenRcaServiceStub(object):
    """See section `Out-of-band (OOB) reporting` of the design document in
    :ref:`https://github.com/envoyproxy/envoy/issues/6614`.

    Out-of-band (OOB) load reporting service for the additional load reporting
    agent that does not sit in the request path. Reports are periodically sampled
    with sufficient frequency to provide temporal association with requests.
    OOB reporting compensates the limitation of in-band reporting in revealing
    costs for backends that do not provide a steady stream of telemetry such as
    long running stream operations and zero QPS services. This is a server
    streaming service, client needs to terminate current RPC and initiate
    a new call to change backend reporting frequency.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCoreMetrics = channel.unary_stream(
                '/udpa.service.orca.v1.OpenRcaService/StreamCoreMetrics',
                request_serializer=udpa_dot_service_dot_orca_dot_v1_dot_orca__pb2.OrcaLoadReportRequest.SerializeToString,
                response_deserializer=udpa_dot_data_dot_orca_dot_v1_dot_orca__load__report__pb2.OrcaLoadReport.FromString,
                _registered_method=True)


class OpenRcaServiceServicer(object):
    """See section `Out-of-band (OOB) reporting` of the design document in
    :ref:`https://github.com/envoyproxy/envoy/issues/6614`.

    Out-of-band (OOB) load reporting service for the additional load reporting
    agent that does not sit in the request path. Reports are periodically sampled
    with sufficient frequency to provide temporal association with requests.
    OOB reporting compensates the limitation of in-band reporting in revealing
    costs for backends that do not provide a steady stream of telemetry such as
    long running stream operations and zero QPS services. This is a server
    streaming service, client needs to terminate current RPC and initiate
    a new call to change backend reporting frequency.
    """

    def StreamCoreMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenRcaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCoreMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCoreMetrics,
                    request_deserializer=udpa_dot_service_dot_orca_dot_v1_dot_orca__pb2.OrcaLoadReportRequest.FromString,
                    response_serializer=udpa_dot_data_dot_orca_dot_v1_dot_orca__load__report__pb2.OrcaLoadReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udpa.service.orca.v1.OpenRcaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('udpa.service.orca.v1.OpenRcaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenRcaService(object):
    """See section `Out-of-band (OOB) reporting` of the design document in
    :ref:`https://github.com/envoyproxy/envoy/issues/6614`.

    Out-of-band (OOB) load reporting service for the additional load reporting
    agent that does not sit in the request path. Reports are periodically sampled
    with sufficient frequency to provide temporal association with requests.
    OOB reporting compensates the limitation of in-band reporting in revealing
    costs for backends that do not provide a steady stream of telemetry such as
    long running stream operations and zero QPS services. This is a server
    streaming service, client needs to terminate current RPC and initiate
    a new call to change backend reporting frequency.
    """

    @staticmethod
    def StreamCoreMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/udpa.service.orca.v1.OpenRcaService/StreamCoreMetrics',
            udpa_dot_service_dot_orca_dot_v1_dot_orca__pb2.OrcaLoadReportRequest.SerializeToString,
            udpa_dot_data_dot_orca_dot_v1_dot_orca__load__report__pb2.OrcaLoadReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
