/* eslint-disable -- generated by infra/aws_tf/scripts/sync-cloudwatch-logging-defaults.mjs */
export const CLOUDWATCH_TERRAFORM_DEFAULTS = {
  workloadKey: "aspire",
  awsRegion: "us-east-1",
  awsAccountId: "017868795096",
  applicationLogsPutPolicyArn: "arn:aws:iam::017868795096:policy/arb_ai_assistant-app-logs-20260517113152714800000001",
  logGroupName: "/arb/arb_ai_assistant/services/aspire",
  otelServiceName: "arb-aspire-host",
  serviceId: "arb-aspire",
  logStreamPrefix: "arb-aspire",
} as const;
