{{- if .Values.backendPool.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-pool-node
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-pool-node
spec:
  clusterIP: None
  selector:
    app: backend-pool-node
  ports:
    - name: http
      port: {{ .Values.podManager.kubernetes.backendPort }}
      targetPort: http
{{- end }}
