{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "routing-tier.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "routing-tier.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "routing-tier.selectorLabels" . | nindent 6 }}
{{- end }}
