# Generated by infra/aws_tf/scripts/sync-cloudwatch-logging-defaults.mjs — do not edit by hand.
"""Terraform-synced defaults for CloudWatch logging (OpenTelemetry → PutLogEvents)."""

DEFAULT_AWS_REGION = "us-east-1"
DEFAULT_AWS_ACCOUNT_ID = "017868795096"
DEFAULT_LOG_GROUP = "/arb/arb_ai_assistant/services/solutions_svc"
LOG_STREAM_PREFIX = "solutions-svc"
DEFAULT_OTEL_SERVICE_NAME = "arb-solutions-svc"
DEFAULT_SERVICE_ID = "arb-solutions-svc"
APPLICATION_LOGS_PUT_POLICY_ARN = "arn:aws:iam::017868795096:policy/arb_ai_assistant-app-logs-20260517113152714800000001"
WORKLOAD_KEY = "solutions_svc"
